version: 2
updates:
  - directory: /
    open-pull-requests-limit: 0
    package-ecosystem: npm
    schedule:
      interval: "daily"

  - directory: /
    open-pull-requests-limit: 0
    package-ecosystem: github-actions
    schedule:
      interval: "daily"
